#!/usr/bin/env python3
"""
commit_validator.py — Conventional Commit Message Validator and Linter

Stdlib-only CLI for validating commit messages against Conventional Commits
rules. Deterministic checks — no API or LLM calls.

Usage:
    python scripts/commit_validator.py validate --message "feat(auth): add refresh token rotation"
    python scripts/commit_validator.py lint --input data/sample-commit-history.json
    python scripts/commit_validator.py report --input data/sample-commit-history.json --output report.md
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from datetime import date
from typing import List, Optional, Tuple


# ---------------------------------------------------------------------------
# ANSI colour helpers
# ---------------------------------------------------------------------------

USE_COLOR = True


def _c(code: str, text: str) -> str:
    if not USE_COLOR:
        return text
    return f"\033[{code}m{text}\033[0m"


def green(t: str) -> str:  return _c("32;1", t)
def yellow(t: str) -> str: return _c("33;1", t)
def red(t: str) -> str:    return _c("31;1", t)
def bold(t: str) -> str:   return _c("1", t)
def dim(t: str) -> str:    return _c("2", t)
def cyan(t: str) -> str:   return _c("36", t)


# ---------------------------------------------------------------------------
# Validation constants (mirrors SKILL.md rules)
# ---------------------------------------------------------------------------

VALID_TYPES = {
    "feat", "fix", "perf", "refactor", "docs",
    "test", "build", "ci", "chore", "style", "revert",
}

# Regex: <type>(<scope>): <summary>  OR  <type>!: <summary>  OR  <type>(<scope>)!: <summary>
SUBJECT_RE = re.compile(
    r"^(?P<type>[a-zA-Z]+)(?:\((?P<scope>[^)]*)\))?(?P<breaking>!)?:\s*(?P<summary>.+)$"
)

# Banned patterns (case-insensitive substring match on the full message)
BANNED_PATTERNS: List[Tuple[str, str]] = [
    ("generated by",  "contains AI/tool attribution 'generated by'"),
    ("claude",        "contains tool attribution 'claude'"),
    ("copilot",       "contains tool attribution 'copilot'"),
    ("chatgpt",       "contains tool attribution 'chatgpt'"),
    ("ai assistant",  "contains tool attribution 'ai assistant'"),
    ("update stuff",  "uses banned vague phrase 'update stuff'"),
    ("fix stuff",     "uses banned vague phrase 'fix stuff'"),
    ("change code",   "uses banned vague phrase 'change code'"),
]

# Single-word banned summaries (exact match on the summary portion, lowercased)
BANNED_SUMMARY_WORDS = {"update", "wip", "misc"}

LENGTH_HARD  = 72   # FAIL if exceeded
LENGTH_SOFT  = 50   # WARN if exceeded

# Imperative check: common non-imperative lead words
NON_IMPERATIVE_WORDS = {
    "added", "adding", "adds",
    "fixed", "fixing", "fixes",
    "updated", "updating", "updates",
    "removed", "removing", "removes",
    "changed", "changing", "changes",
    "implemented", "implementing", "implements",
    "refactored", "refactoring", "refactors",
    "created", "creating", "creates",
    "deleted", "deleting", "deletes",
    "moved", "moving", "moves",
    "renamed", "renaming", "renames",
}


# ---------------------------------------------------------------------------
# Result dataclass (plain class for 3.7+ compat without dataclasses import)
# ---------------------------------------------------------------------------

class ValidationResult:
    __slots__ = ("status", "message", "issues", "suggestion")

    def __init__(
        self,
        status: str,
        message: str,
        issues: List[str],
        suggestion: Optional[str] = None,
    ) -> None:
        self.status = status          # "PASS", "WARN", "FAIL"
        self.message = message
        self.issues = issues
        self.suggestion = suggestion


# ---------------------------------------------------------------------------
# Core validation logic
# ---------------------------------------------------------------------------

def validate_message(msg: str) -> ValidationResult:
    """
    Validate a single commit message subject line.

    Returns a ValidationResult with status PASS / WARN / FAIL,
    a list of issue descriptions, and an optional suggested rewrite.
    """
    raw = msg.strip()
    issues: List[str] = []
    warnings: List[str] = []

    # --- banned patterns (check the full raw message, case-insensitive) ---
    lower_raw = raw.lower()
    for pattern, description in BANNED_PATTERNS:
        if pattern in lower_raw:
            issues.append(description)

    # --- structural parse ---
    match = SUBJECT_RE.match(raw)
    if not match:
        issues.append("missing type prefix — expected '<type>: <summary>' or '<type>(<scope>): <summary>'")
        # Can't continue checking type/scope/summary without a parse result
        status = "FAIL" if issues else "PASS"
        return ValidationResult(status, raw, issues + warnings)

    commit_type  = match.group("type")
    scope        = match.group("scope") or ""
    summary      = match.group("summary").strip()

    # --- type validity ---
    if commit_type.lower() not in VALID_TYPES:
        issues.append(
            f"'{commit_type}' is not a valid Conventional Commits type "
            f"(valid: {', '.join(sorted(VALID_TYPES))})"
        )
    elif commit_type != commit_type.lower():
        issues.append(f"type '{commit_type}' must be lowercase")

    # --- scope format ---
    if scope and scope != scope.lower():
        issues.append(f"scope '({scope})' must be lowercase")

    # --- summary checks ---
    if not summary:
        issues.append("summary is empty")
    else:
        # trailing period
        if summary.endswith("."):
            issues.append("summary must not end with a period")

        # banned single-word summaries
        if summary.lower() in BANNED_SUMMARY_WORDS:
            issues.append(f"summary '{summary}' is too vague — use a specific, imperative description")

        # imperative check (first word)
        first_word = summary.split()[0].lower() if summary.split() else ""
        if first_word in NON_IMPERATIVE_WORDS:
            warnings.append(
                f"summary appears to start with past/present-continuous tense ('{first_word}') — "
                "prefer imperative mood (e.g., 'add' not 'added', 'fix' not 'fixing')"
            )

    # --- length checks ---
    total_len = len(raw)
    if total_len > LENGTH_HARD:
        issues.append(
            f"subject line is {total_len} chars — exceeds hard limit of {LENGTH_HARD}"
        )
    elif total_len > LENGTH_SOFT:
        warnings.append(
            f"subject line is {total_len} chars — over preferred limit of {LENGTH_SOFT} "
            f"(hard limit is {LENGTH_HARD})"
        )

    # --- determine status ---
    if issues:
        status = "FAIL"
    elif warnings:
        status = "WARN"
    else:
        status = "PASS"

    all_issues = issues + warnings

    # --- build suggestion ---
    suggestion = _build_suggestion(raw, match, issues, warnings)

    return ValidationResult(status, raw, all_issues, suggestion)


def _build_suggestion(
    raw: str,
    match: "re.Match[str]",
    errors: List[str],
    warnings: List[str],
) -> Optional[str]:
    """
    Produce a suggested rewrite only when there are fixable issues.
    Handles the most common mechanical fixes; complex cases prompt human review.
    """
    if not errors and not warnings:
        return None

    commit_type = match.group("type").lower()
    scope = match.group("scope") or ""
    summary = match.group("summary").strip() if match.group("summary") else ""

    # Ensure type is valid (default to 'chore' if unknown)
    if commit_type not in VALID_TYPES:
        commit_type = "chore"

    # Lowercase scope
    scope = scope.lower()

    # Strip trailing period from summary
    if summary.endswith("."):
        summary = summary[:-1]

    # Replace banned single-word summaries with a prompt
    if summary.lower() in BANNED_SUMMARY_WORDS:
        summary = "<describe the specific change here>"

    # Remove tool attribution tokens from summary (best-effort)
    for pattern, _ in BANNED_PATTERNS:
        summary = re.sub(re.escape(pattern), "", summary, flags=re.IGNORECASE).strip()

    # Reconstruct
    if scope:
        rebuilt = f"{commit_type}({scope}): {summary}"
    else:
        rebuilt = f"{commit_type}: {summary}"

    # Only return if different from original
    if rebuilt.strip() == raw.strip():
        return None
    return rebuilt


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load_history(path: str) -> List[dict]:
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except FileNotFoundError:
        print(f"ERROR: file not found: {path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as exc:
        print(f"ERROR: invalid JSON in {path}: {exc}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(data, list):
        print(f"ERROR: {path} must be a JSON array of commit objects.", file=sys.stderr)
        sys.exit(1)

    return data


# ---------------------------------------------------------------------------
# Status label helpers
# ---------------------------------------------------------------------------

def colorize_status(status: str) -> str:
    if status == "PASS":
        return green(status)
    if status == "WARN":
        return yellow(status)
    return red(status)


# ---------------------------------------------------------------------------
# Subcommand: validate
# ---------------------------------------------------------------------------

def cmd_validate(args: argparse.Namespace) -> int:
    result = validate_message(args.message)

    print()
    print(bold("VALIDATION: " + result.status))
    print()
    print(f"Message:")
    print(f"  {result.message}")
    print()

    if result.issues:
        print("Issues:")
        for issue in result.issues:
            print(f"  - {issue}")
        print()

    if result.suggestion:
        print("Suggested fix:")
        print(f"  {result.suggestion}")
        print()

    if result.status == "PASS":
        print(green("  OK — message passes all checks."))
    elif result.status == "WARN":
        print(yellow("  WARN — message passes but has style warnings."))
    else:
        print(red("  FAIL — message violates one or more commit policy rules."))

    print()
    return 0 if result.status in ("PASS", "WARN") else 1


# ---------------------------------------------------------------------------
# Subcommand: lint
# ---------------------------------------------------------------------------

def cmd_lint(args: argparse.Namespace) -> int:
    commits = load_history(args.input)

    results: List[Tuple[dict, ValidationResult]] = []
    for commit in commits:
        msg = commit.get("message", "")
        results.append((commit, validate_message(msg)))

    total    = len(results)
    passing  = sum(1 for _, r in results if r.status == "PASS")
    warning  = sum(1 for _, r in results if r.status == "WARN")
    failing  = sum(1 for _, r in results if r.status == "FAIL")

    # Collect violation type counts
    violation_counter: Counter = Counter()
    for _, r in results:
        for issue in r.issues:
            # Categorise into coarse buckets for the summary
            violation_counter[_categorise_issue(issue)] += 1

    print()
    print(bold(f"  COMMIT HISTORY LINT"))
    print(bold(f"  File:    {args.input}"))
    print(bold(f"  Commits: {total}"))
    print()

    # Per-message output
    for commit, result in results:
        hash_str  = commit.get("hash", "???????")
        author    = commit.get("author", "")
        status_lbl = colorize_status(result.status)

        print(f"  [{status_lbl}] {hash_str}  {dim(author)}")
        print(f"         {result.message}")
        if result.issues:
            for issue in result.issues:
                print(f"         {dim('→')} {issue}")
        if result.suggestion:
            print(f"         {cyan('✎')} {cyan(result.suggestion)}")
        print()

    # Summary statistics
    pct_pass = (passing / total * 100) if total else 0
    pct_warn = (warning / total * 100) if total else 0
    pct_fail = (failing / total * 100) if total else 0

    print(bold("  SUMMARY"))
    print()
    print(f"  {green('PASS')}  {passing:>3} / {total}  ({pct_pass:.0f}%)")
    print(f"  {yellow('WARN')}  {warning:>3} / {total}  ({pct_warn:.0f}%)")
    print(f"  {red('FAIL')}  {failing:>3} / {total}  ({pct_fail:.0f}%)")
    print()

    if violation_counter:
        print(bold("  MOST COMMON VIOLATIONS"))
        print()
        for violation, count in violation_counter.most_common(8):
            print(f"  {count:>3}x  {violation}")
        print()

    return 0 if failing == 0 else 1


def _categorise_issue(issue: str) -> str:
    """Map a raw issue string to a coarse violation category."""
    lower = issue.lower()
    if "type prefix" in lower or "type'" in lower or "valid" in lower:
        return "missing or invalid type prefix"
    if "tool attribution" in lower or "generated by" in lower:
        return "tool/AI attribution in message"
    if "vague" in lower or "banned" in lower or "too vague" in lower:
        return "vague or banned summary phrase"
    if "lowercase" in lower and "type" in lower:
        return "type not lowercase"
    if "lowercase" in lower and "scope" in lower:
        return "scope not lowercase"
    if "period" in lower:
        return "trailing period on summary"
    if "imperative" in lower or "tense" in lower:
        return "non-imperative summary tense"
    if "char" in lower or "limit" in lower or "length" in lower:
        return "subject line too long"
    if "empty" in lower:
        return "empty summary"
    return "other violation"


# ---------------------------------------------------------------------------
# Subcommand: report
# ---------------------------------------------------------------------------

def cmd_report(args: argparse.Namespace) -> int:
    commits = load_history(args.input)
    today = date.today().isoformat()

    results: List[Tuple[dict, ValidationResult]] = []
    for commit in commits:
        msg = commit.get("message", "")
        results.append((commit, validate_message(msg)))

    total   = len(results)
    passing = sum(1 for _, r in results if r.status == "PASS")
    warning = sum(1 for _, r in results if r.status == "WARN")
    failing = sum(1 for _, r in results if r.status == "FAIL")

    violation_counter: Counter = Counter()
    for _, r in results:
        for issue in r.issues:
            violation_counter[_categorise_issue(issue)] += 1

    lines: List[str] = []
    add = lines.append

    add("# Commit Message Quality Report")
    add("")
    add(f"**Source file:** `{os.path.basename(args.input)}`  ")
    add(f"**Report generated:** {today}  ")
    add(f"**Total commits analysed:** {total}  ")
    add("")

    add("## Executive Summary")
    add("")
    add("| Status | Count | Percentage |")
    add("|--------|------:|-----------:|")
    pct_p = f"{passing / total * 100:.0f}%" if total else "—"
    pct_w = f"{warning / total * 100:.0f}%" if total else "—"
    pct_f = f"{failing / total * 100:.0f}%" if total else "—"
    add(f"| PASS | {passing} | {pct_p} |")
    add(f"| WARN | {warning} | {pct_w} |")
    add(f"| FAIL | {failing} | {pct_f} |")
    add(f"| **Total** | **{total}** | 100% |")
    add("")

    if violation_counter:
        add("## Most Common Violations")
        add("")
        add("| Violation | Count |")
        add("|-----------|------:|")
        for violation, count in violation_counter.most_common():
            add(f"| {violation} | {count} |")
        add("")

    add("## Per-Commit Results")
    add("")
    add("| Hash | Status | Author | Message |")
    add("|------|--------|--------|---------|")
    for commit, result in results:
        hash_str = commit.get("hash", "???????")
        author   = commit.get("author", "")
        # Escape pipes in message
        msg_safe = result.message.replace("|", "\\|")
        add(f"| `{hash_str}` | {result.status} | {author} | {msg_safe} |")
    add("")

    # Detailed section for non-passing commits
    non_passing = [(c, r) for c, r in results if r.status != "PASS"]
    if non_passing:
        add("## Commits Requiring Attention")
        add("")
        for commit, result in non_passing:
            hash_str = commit.get("hash", "???????")
            author   = commit.get("author", "")
            cdate    = commit.get("date", "")
            add(f"### `{hash_str}` — {result.status}")
            add("")
            add(f"- **Author:** {author}")
            add(f"- **Date:** {cdate}")
            add(f"- **Message:** `{result.message}`")
            add("")
            if result.issues:
                add("**Issues:**")
                add("")
                for issue in result.issues:
                    add(f"- {issue}")
                add("")
            if result.suggestion:
                add(f"**Suggested rewrite:** `{result.suggestion}`")
                add("")
    else:
        add("## Commits Requiring Attention")
        add("")
        add("_All commits pass. No attention required._")
        add("")

    add("## Validation Rules Reference")
    add("")
    add("| Rule | Threshold | Severity |")
    add("|------|-----------|----------|")
    add("| Type prefix required | `<type>: <summary>` or `<type>(<scope>): <summary>` | FAIL |")
    add(f"| Valid types | {', '.join(f'`{t}`' for t in sorted(VALID_TYPES))} | FAIL |")
    add("| Type must be lowercase | — | FAIL |")
    add("| Scope must be lowercase | — | FAIL |")
    add("| Summary must be imperative | no trailing -ed/-ing on first word | WARN |")
    add("| No trailing period | — | FAIL |")
    add(f"| Subject line length (soft) | ≤{LENGTH_SOFT} chars | WARN |")
    add(f"| Subject line length (hard) | ≤{LENGTH_HARD} chars | FAIL |")
    add("| Banned summary phrases | update, wip, misc, update stuff, fix stuff, change code | FAIL |")
    add("| No tool attribution | generated by, claude, copilot, chatgpt, ai assistant | FAIL |")
    add("")

    add("---")
    add("_Report generated by commit_validator.py — dev-git-commit-message skill_")

    report_text = "\n".join(lines)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as fh:
            fh.write(report_text)
        print(f"Report written to: {args.output}")
    else:
        print(report_text)

    return 0


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="commit_validator.py",
        description="Conventional Commit Message Validator and Linter (stdlib only)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/commit_validator.py validate --message "feat(auth): add refresh token rotation"
  python scripts/commit_validator.py lint --input data/sample-commit-history.json
  python scripts/commit_validator.py report --input data/sample-commit-history.json
  python scripts/commit_validator.py report --input data/sample-commit-history.json --output report.md
        """.strip(),
    )
    parser.add_argument(
        "--no-color",
        action="store_true",
        help="Disable ANSI colour output (useful for CI logs)",
    )

    sub = parser.add_subparsers(dest="command", metavar="COMMAND")
    sub.required = True

    # --- validate ---
    p_validate = sub.add_parser(
        "validate",
        help="Validate a single commit message",
        description=(
            "Validate one commit message against Conventional Commits rules. "
            "Checks type prefix, valid type, scope case, imperative mood, "
            "length, trailing period, banned phrases, and tool attribution."
        ),
    )
    p_validate.add_argument(
        "--message", "-m",
        required=True,
        metavar="MSG",
        help="Commit message subject line to validate",
    )

    # --- lint ---
    p_lint = sub.add_parser(
        "lint",
        help="Lint a batch of commit messages from a JSON history file",
        description=(
            "Read a JSON commit history array and validate every message. "
            "Prints per-message PASS/WARN/FAIL, then a summary with "
            "statistics and most common violation types."
        ),
    )
    p_lint.add_argument(
        "--input", "-i",
        required=True,
        metavar="JSON_FILE",
        help="Path to commit history JSON file (array of commit objects)",
    )

    # --- report ---
    p_report = sub.add_parser(
        "report",
        help="Generate a full Markdown commit quality report",
        description=(
            "Produce a full Markdown report: executive summary, violation "
            "breakdown, per-commit table, and detailed attention list for "
            "non-passing commits."
        ),
    )
    p_report.add_argument(
        "--input", "-i",
        required=True,
        metavar="JSON_FILE",
        help="Path to commit history JSON file",
    )
    p_report.add_argument(
        "--output", "-o",
        metavar="FILE",
        help="Write Markdown report to this file (default: stdout)",
    )

    return parser


def main() -> int:
    global USE_COLOR

    # Handle --no-color before full parse so it works in any position
    if "--no-color" in sys.argv:
        USE_COLOR = False
        sys.argv = [a for a in sys.argv if a != "--no-color"]

    parser = build_parser()
    args = parser.parse_args()

    dispatch = {
        "validate": cmd_validate,
        "lint":     cmd_lint,
        "report":   cmd_report,
    }
    return dispatch[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
