#!/usr/bin/env python3
"""PreToolUse (Claude, matcher Write|Edit): deny edits to an existing lint or format config.

When a check fails, an agent can pass it by loosening the rule instead of fixing the code.
This guard denies a Write or Edit to a protected config file that already exists, and allows
its first creation. Template and rationale: skills/universal/agents-hooks/references/
hook-templates.md, "Claude: Lint and Format Config Guard".

Fails closed: unreadable input, a missing file_path or an internal error exits 2.
A policy deny exits 2 with the reason on stderr. Limit: a Bash write such as `sed -i`
passes this guard; it sees only Write and Edit.
"""
import fnmatch
import json
import os
import sys

PROTECTED = [
    ".eslintrc*", "eslint.config.*", ".eslintignore", ".prettierrc*",
    "prettier.config.*", ".prettierignore", "ruff.toml", ".ruff.toml",
    "biome.json", "biome.jsonc", ".flake8", ".stylelintrc*",
]


def main() -> int:
    try:
        data = json.load(sys.stdin)
        if data.get("tool_name") not in ("Write", "Edit"):
            return 0
        path = (data.get("tool_input") or {}).get("file_path") or ""
        if not path:
            print("config guard: no file_path in input, refusing", file=sys.stderr)
            return 2
        # Lowercase: macOS file systems usually ignore case, so .ESLintrc.json is .eslintrc.json.
        names = {os.path.basename(p).lower() for p in (path, os.path.realpath(path))}  # symlink to a config
        name = next((n for n in sorted(names) if any(fnmatch.fnmatch(n, p) for p in PROTECTED)), None)
        if name and os.path.exists(path):
            print(f"{name} is a protected lint or format config. Fix the code so the "
                  "existing rule passes, or ask the user to change the rule. "
                  "Do not edit this file and do not disable this hook.", file=sys.stderr)
            return 2
        return 0
    except Exception as exc:  # fail closed
        print(f"config guard: {type(exc).__name__}: {exc}, refusing", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
