#!/usr/bin/env bash
# generate-api-catalog.sh — collect API contracts across the portfolio
# into a single catalog stub under context/overview/. Read-only scan.
# Generic: extend the FIND patterns for your contract formats.
set -euo pipefail

HUB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REPOS_ROOT="${1:-$(dirname "$HUB_DIR")}"
OUT="$HUB_DIR/context/overview/api-catalog.md"

{
  echo "# API Catalog"
  echo
  echo "> Generated by context/scripts/generate-api-catalog.sh on $(date -u +%Y-%m-%d)."
  echo "> One row per discovered contract. Replace/extend patterns as needed."
  echo
  echo "| Repo | Contract file | Type |"
  echo "|------|---------------|------|"
  shopt -s nullglob
  for repo in "$REPOS_ROOT"/*/; do
    name="$(basename "$repo")"
    [ "$repo" = "$HUB_DIR/" ] && continue
    [ -d "$repo/.git" ] || continue
    find "$repo" \
      \( -path '*/node_modules/*' -o -path '*/.git/*' -o -path '*/bin/*' \
         -o -path '*/obj/*' -o -path '*/.build/*' \) -prune -o \
      \( -iname 'openapi*.y*ml' -o -iname 'swagger*.json' \
         -o -iname '*.proto' -o -iname 'asyncapi*.y*ml' \) -print 2>/dev/null \
    | while read -r c; do
        rel="${c#"$repo"}"
        case "$c" in
          *.proto)            t="gRPC/proto" ;;
          *asyncapi*)         t="AsyncAPI" ;;
          *swagger*|*openapi*) t="OpenAPI" ;;
          *)                  t="unknown" ;;
        esac
        echo "| $name | $rel | $t |"
      done
  done
} > "$OUT"
echo "Wrote $OUT"
