#!/usr/bin/env python3
"""
commit_validator.py — Conventional Commit Message Validator and Linter

Stdlib-only CLI for validating commit messages against Conventional Commits
rules. Deterministic checks — no API or LLM calls.

Usage:
    python scripts/commit_validator.py validate --message "feat(auth): add refresh token rotation"
    python scripts/commit_validator.py lint --input data/sample-commit-history.json
    python scripts/commit_validator.py report --input data/sample-commit-history.json --output report.md
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from datetime import date
from typing import List, Optional, Tuple


# ---------------------------------------------------------------------------
# ANSI colour helpers
# ---------------------------------------------------------------------------

USE_COLOR = True


def _c(code: str, text: str) -> str:
    if not USE_COLOR:
        return text
    return f"\033[{code}m{text}\033[0m"


def green(t: str) -> str:  return _c("32;1", t)
def yellow(t: str) -> str: return _c("33;1", t)
def red(t: str) -> str:    return _c("31;1", t)
def bold(t: str) -> str:   return _c("1", t)
def dim(t: str) -> str:    return _c("2", t)
def cyan(t: str) -> str:   return _c("36", t)


# ---------------------------------------------------------------------------
# Validation constants (mirrors SKILL.md rules)
# ---------------------------------------------------------------------------

VALID_TYPES = {
    "feat", "fix", "perf", "refactor", "docs",
    "test", "build", "ci", "chore", "style", "revert",
}

# Regex: <type>(<scope>): <summary>  OR  <type>!: <summary>  OR  <type>(<scope>)!: <summary>
SUBJECT_RE = re.compile(
    r"^(?P<type>[a-zA-Z]+)(?:\((?P<scope>[^)]*)\))?(?P<breaking>!)?: +(?P<summary>\S.*)$"
)
SCOPE_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

# Git's default revert subject: Revert "<original subject>"
GIT_REVERT_RE = re.compile(r'^Revert ".+"$')

# Trailer / footer line: "Token: value" or "Token #value" (git-interpret-trailers),
# plus the Conventional Commits "BREAKING CHANGE:" / "BREAKING-CHANGE:" footer.
TRAILER_RE = re.compile(
    r"^(?P<key>BREAKING[ -]CHANGE|[A-Za-z][A-Za-z0-9-]*)(?:(?::\s|\s#)(?P<value>.*)|:)$"
)
BREAKING_KEYS = {"breaking change", "breaking-change"}

# Trailers the skill documents as acceptable (see "AI-Authored Commits" in
# SKILL.md). `Assisted-by:` is the recommended default attribution trailer;
# `Claude-Session:` is a session-link trailer; `Audit-*` (Audit-Batch,
# Audit-Skill, ...) are audit-trail trailers. All belong in the final block.
ALLOWED_AI_TRAILERS = {"assisted-by", "claude-session"}
ALLOWED_AI_TRAILER_PREFIXES = ("audit-",)

# AI tool names used to detect attribution inside *trailers* only
# (a scope such as `feat(claude-client)` is not attribution).
AI_TOOL_RE = re.compile(r"\b(claude|copilot|chatgpt|gpt-?\d|gemini|codex|cursor)\b", re.IGNORECASE)

# Banned phrases (case-insensitive substring match on subject + body prose,
# never on allowed trailers). Mirrors the SKILL.md "AI-Authored Commits" list.
BANNED_PATTERNS: List[Tuple[str, str]] = [
    ("generated by",  "contains AI/tool attribution 'generated by'"),
    ("via claude",    "contains tool attribution 'via claude'"),
    ("via copilot",   "contains tool attribution 'via copilot'"),
    ("chatgpt",       "contains tool attribution 'chatgpt'"),
    ("ai assistant",  "contains tool attribution 'ai assistant'"),
    ("update stuff",  "uses banned vague phrase 'update stuff'"),
    ("fix stuff",     "uses banned vague phrase 'fix stuff'"),
    ("change code",   "uses banned vague phrase 'change code'"),
]

# Single-word banned summaries (exact match on the summary portion, lowercased)
BANNED_SUMMARY_WORDS = {"update", "wip", "misc"}

LENGTH_HARD  = 72   # FAIL if exceeded (subject line only)
LENGTH_SOFT  = 50   # WARN if exceeded (subject line only)

# Imperative check: common non-imperative lead words -> imperative form
IMPERATIVE_FIX = {
    "added": "add", "adding": "add", "adds": "add",
    "fixed": "fix", "fixing": "fix", "fixes": "fix",
    "updated": "update", "updating": "update", "updates": "update",
    "removed": "remove", "removing": "remove", "removes": "remove",
    "changed": "change", "changing": "change", "changes": "change",
    "implemented": "implement", "implementing": "implement", "implements": "implement",
    "refactored": "refactor", "refactoring": "refactor", "refactors": "refactor",
    "created": "create", "creating": "create", "creates": "create",
    "deleted": "delete", "deleting": "delete", "deletes": "delete",
    "moved": "move", "moving": "move", "moves": "move",
    "renamed": "rename", "renaming": "rename", "renames": "rename",
}
NON_IMPERATIVE_WORDS = set(IMPERATIVE_FIX)


# ---------------------------------------------------------------------------
# Result dataclass (plain class for 3.7+ compat without dataclasses import)
# ---------------------------------------------------------------------------

class ValidationResult:
    __slots__ = ("status", "message", "issues", "suggestion")

    def __init__(
        self,
        status: str,
        message: str,
        issues: List[str],
        suggestion: Optional[str] = None,
    ) -> None:
        self.status = status          # "PASS", "WARN", "FAIL"
        self.message = message        # subject line (first line) for display
        self.issues = issues
        self.suggestion = suggestion


# ---------------------------------------------------------------------------
# Message parsing
# ---------------------------------------------------------------------------

def split_message(msg: str) -> Tuple[str, List[str], List[Tuple[str, str]]]:
    """
    Split a full commit message into (subject, body_lines, trailers).

    The subject is the first line. Trailers are the final paragraph when every
    non-continuation line in it is a `Key: value` trailer or a
    `BREAKING CHANGE:` footer. Everything between is body prose.
    """
    lines = [ln.rstrip() for ln in msg.strip().splitlines()]
    if not lines:
        return "", [], []
    subject, rest = lines[0].strip(), lines[1:]

    # Last paragraph = lines after the final blank line in `rest`.
    last_blank = max((i for i, ln in enumerate(rest) if not ln.strip()), default=-1)
    candidate = rest[last_blank + 1:]
    trailers: List[Tuple[str, str]] = []
    is_trailer_block = bool(candidate) and last_blank >= 0
    for ln in candidate:
        if ln[:1].isspace() and trailers:          # folded continuation line
            key, val = trailers[-1]
            trailers[-1] = (key, f"{val} {ln.strip()}")
            continue
        m = TRAILER_RE.match(ln)
        if not m:
            is_trailer_block = False
            break
        trailers.append((m.group("key"), (m.group("value") or "").strip()))

    if is_trailer_block:
        body = rest[:last_blank]
    else:
        body, trailers = rest, []
    while body and not body[0].strip():
        body = body[1:]
    while body and not body[-1].strip():
        body = body[:-1]
    return subject, body, trailers


# ---------------------------------------------------------------------------
# Core validation logic
# ---------------------------------------------------------------------------

def _finish(subject: str, issues: List[str], warnings: List[str],
            suggestion: Optional[str] = None) -> ValidationResult:
    status = "FAIL" if issues else ("WARN" if warnings else "PASS")
    return ValidationResult(status, subject, issues + warnings, suggestion)


def _check_summary(summary: str, issues: List[str], warnings: List[str]) -> None:
    """Summary rules shared by conventional and plain-subject modes."""
    if not summary:
        issues.append("summary is empty")
        return
    if summary.endswith("."):
        issues.append("summary must not end with a period")
    if summary.lower() in BANNED_SUMMARY_WORDS:
        issues.append(f"summary '{summary}' is too vague — use a specific, imperative description")
    first_word = summary.split()[0].lower()
    if first_word in NON_IMPERATIVE_WORDS:
        warnings.append(
            f"summary appears to start with past/present-continuous tense ('{first_word}') — "
            "prefer imperative mood (e.g., 'add' not 'added', 'fix' not 'fixing')"
        )


def _plain_suggestion(subject: str, issues: List[str], warnings: List[str]) -> Optional[str]:
    """Mechanical fixes for a plain subject: trailing period and non-imperative first word."""
    if not issues and not warnings:
        return None
    fixed = subject[:-1] if subject.endswith(".") else subject
    words = fixed.split(" ", 1)
    if words and words[0].lower() in IMPERATIVE_FIX:
        fix = IMPERATIVE_FIX[words[0].lower()]
        words[0] = fix.capitalize() if words[0][:1].isupper() else fix
        fixed = " ".join(words)
    return None if fixed == subject else fixed


def validate_message(msg: str, type_prefix: bool = True) -> ValidationResult:
    """
    Validate a full commit message (subject, optional body, optional trailers).

    With type_prefix=False (CLI `--no-type-prefix`) the type/scope rules are
    skipped for subjects that are not Conventional Commits: the whole subject is
    treated as the summary. Every other rule still applies.

    The type prefix, summary, and length rules apply to the subject line only.
    Bodies, `BREAKING CHANGE:` footers, git's default `Revert "..."` subject,
    and the `Assisted-by:`, `Claude-Session:` and `Audit-*` trailers are accepted.

    Returns a ValidationResult with status PASS / WARN / FAIL,
    a list of issue descriptions, and an optional suggested rewrite.
    """
    subject, body, trailers = split_message(msg)
    issues: List[str] = []
    warnings: List[str] = []

    raw_lines = msg.strip().splitlines()
    if len(raw_lines) > 1 and raw_lines[1].strip():
        warnings.append("line 2 should be blank — separate the subject from the body")

    # --- banned phrases (subject + body prose; trailers handled separately) ---
    prose = "\n".join([subject] + body).lower()
    for pattern, description in BANNED_PATTERNS:
        if pattern in prose:
            issues.append(description)

    # --- trailers ---
    for key, value in trailers:
        k = key.lower()
        if k in BREAKING_KEYS:
            if not value:
                issues.append("BREAKING CHANGE footer has no description")
            continue
        if k in ALLOWED_AI_TRAILERS or k.startswith(ALLOWED_AI_TRAILER_PREFIXES):
            continue
        if AI_TOOL_RE.search(key) or AI_TOOL_RE.search(value):
            issues.append(
                f"trailer '{key}:' contains AI tool attribution — only "
                "'Assisted-by:', 'Claude-Session:' and 'Audit-*' trailers are allowed "
                "(see SKILL.md AI-Authored Commits)"
            )

    # --- allowed audit/attribution trailers stranded in the body ---
    # Trailers are read from the final paragraph only, so a line that sits in
    # an earlier paragraph is invisible to trailer tooling.
    for ln in body:
        m = TRAILER_RE.match(ln)
        if m:
            k = m.group("key").lower()
            if k in ALLOWED_AI_TRAILERS or k.startswith(ALLOWED_AI_TRAILER_PREFIXES):
                warnings.append(
                    f"trailer '{m.group('key')}:' is outside the final paragraph — keep "
                    "Assisted-by/Claude-Session/Audit-* lines together in one final block"
                )

    # --- length checks (subject line only) ---
    subj_len = len(subject)
    if subj_len > LENGTH_HARD:
        issues.append(f"subject line is {subj_len} chars — exceeds hard limit of {LENGTH_HARD}")
    elif subj_len > LENGTH_SOFT:
        warnings.append(
            f"subject line is {subj_len} chars — over preferred limit of {LENGTH_SOFT} "
            f"(hard limit is {LENGTH_HARD})"
        )

    # --- git's default revert subject is accepted as-is ---
    if GIT_REVERT_RE.match(subject):
        return _finish(subject, issues, warnings)

    # --- structural parse (subject only) ---
    match = SUBJECT_RE.match(subject)
    if not type_prefix and not (match and match.group("type").lower() in VALID_TYPES):
        _check_summary(subject, issues, warnings)
        return _finish(subject, issues, warnings, _plain_suggestion(subject, issues, warnings))
    if not match:
        issues.append("missing type prefix — expected '<type>: <summary>' or '<type>(<scope>): <summary>'")
        return _finish(subject, issues, warnings)

    commit_type  = match.group("type")
    scope        = match.group("scope")
    summary      = match.group("summary").strip()

    # --- type validity ---
    if commit_type.lower() not in VALID_TYPES:
        issues.append(
            f"'{commit_type}' is not a supported bundled policy type "
            f"(valid: {', '.join(sorted(VALID_TYPES))})"
        )
    elif commit_type != commit_type.lower():
        issues.append(f"type '{commit_type}' must be lowercase")

    # --- scope format ---
    if scope is not None and not SCOPE_RE.fullmatch(scope):
        issues.append(f"scope '({scope})' must be nonempty lowercase kebab-case")

    # --- summary checks ---
    _check_summary(summary, issues, warnings)

    suggestion = _build_suggestion(subject, match, issues, warnings)
    return _finish(subject, issues, warnings, suggestion)


def _build_suggestion(
    subject: str,
    match: "re.Match[str]",
    errors: List[str],
    warnings: List[str],
) -> Optional[str]:
    """
    Produce a suggested subject rewrite only when there are fixable issues.
    Handles the most common mechanical fixes; complex cases prompt human review.
    """
    if not errors and not warnings:
        return None

    commit_type = match.group("type").lower()
    scope = (match.group("scope") or "").lower()
    breaking = match.group("breaking") or ""
    summary = match.group("summary").strip() if match.group("summary") else ""

    if commit_type not in VALID_TYPES:
        commit_type = "chore"
    if summary.endswith("."):
        summary = summary[:-1]
    if summary.lower() in BANNED_SUMMARY_WORDS:
        summary = "<describe the specific change here>"
    if any(p in e for e in errors for p in ("attribution", "vague phrase")):
        for pattern, _ in BANNED_PATTERNS:
            summary = re.sub(re.escape(pattern), "", summary, flags=re.IGNORECASE)
        summary = AI_TOOL_RE.sub("", summary)
        summary = re.sub(r"\s+", " ", summary).strip(" -\u2014:;,")

    # Imperative mood: replace a non-imperative first word
    words = summary.split(" ", 1)
    if words and words[0].lower() in IMPERATIVE_FIX:
        words[0] = IMPERATIVE_FIX[words[0].lower()]
        summary = " ".join(words)

    prefix = f"{commit_type}({scope})" if scope else commit_type
    rebuilt = f"{prefix}{breaking}: {summary}"
    if rebuilt.strip() == subject.strip():
        return None
    return rebuilt


# ---------------------------------------------------------------------------
# I/O helpers
# ---------------------------------------------------------------------------

def load_history(path: str) -> List[dict]:
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except FileNotFoundError:
        print(f"ERROR: file not found: {path}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as exc:
        print(f"ERROR: invalid JSON in {path}: {exc}", file=sys.stderr)
        sys.exit(1)
    except (OSError, UnicodeError) as exc:
        print(f"ERROR: cannot read {path}: {exc}", file=sys.stderr)
        sys.exit(1)

    if not isinstance(data, list):
        print(f"ERROR: {path} must be a JSON array of commit objects.", file=sys.stderr)
        sys.exit(1)
    if not data:
        print(f"ERROR: {path} contains no commit records to validate.", file=sys.stderr)
        sys.exit(1)

    for index, commit in enumerate(data):
        if not isinstance(commit, dict):
            print(f"ERROR: {path} record {index} must be a commit object.", file=sys.stderr)
            sys.exit(1)
        for field in ("message", "hash", "author", "date"):
            if (field == "message" or field in commit) and not isinstance(commit.get(field), str):
                print(f"ERROR: {path} record {index} requires a string '{field}'.", file=sys.stderr)
                sys.exit(1)

    return data


# ---------------------------------------------------------------------------
# Status label helpers
# ---------------------------------------------------------------------------

def colorize_status(status: str) -> str:
    if status == "PASS":
        return green(status)
    if status == "WARN":
        return yellow(status)
    return red(status)


# ---------------------------------------------------------------------------
# Subcommand: validate
# ---------------------------------------------------------------------------

def cmd_validate(args: argparse.Namespace) -> int:
    result = validate_message(args.message, type_prefix=not args.no_type_prefix)

    print()
    print(bold("VALIDATION: " + result.status))
    print()
    print(f"Message:")
    print(f"  {result.message}")
    print()

    if result.issues:
        print("Issues:")
        for issue in result.issues:
            print(f"  - {issue}")
        print()

    if result.suggestion:
        print("Suggested fix:")
        print(f"  {result.suggestion}")
        print()

    if result.status == "PASS":
        print(green("  OK — message passes all checks."))
    elif result.status == "WARN":
        print(yellow("  WARN — message passes but has style warnings."))
    else:
        print(red("  FAIL — message violates one or more commit policy rules."))

    print()
    return 0 if result.status in ("PASS", "WARN") else 1


# ---------------------------------------------------------------------------
# Subcommand: lint
# ---------------------------------------------------------------------------

def cmd_lint(args: argparse.Namespace) -> int:
    commits = load_history(args.input)

    results: List[Tuple[dict, ValidationResult]] = []
    for commit in commits:
        msg = commit.get("message", "")
        results.append((commit, validate_message(msg, type_prefix=not args.no_type_prefix)))

    total    = len(results)
    passing  = sum(1 for _, r in results if r.status == "PASS")
    warning  = sum(1 for _, r in results if r.status == "WARN")
    failing  = sum(1 for _, r in results if r.status == "FAIL")

    # Collect violation type counts
    violation_counter: Counter = Counter()
    for _, r in results:
        for issue in r.issues:
            # Categorise into coarse buckets for the summary
            violation_counter[_categorise_issue(issue)] += 1

    print()
    print(bold(f"  COMMIT HISTORY LINT"))
    print(bold(f"  File:    {args.input}"))
    print(bold(f"  Commits: {total}"))
    print()

    # Per-message output
    for commit, result in results:
        hash_str  = commit.get("hash", "???????")
        author    = commit.get("author", "")
        status_lbl = colorize_status(result.status)

        print(f"  [{status_lbl}] {hash_str}  {dim(author)}")
        print(f"         {result.message}")
        if result.issues:
            for issue in result.issues:
                print(f"         {dim('→')} {issue}")
        if result.suggestion:
            print(f"         {cyan('✎')} {cyan(result.suggestion)}")
        print()

    # Summary statistics
    pct_pass = (passing / total * 100) if total else 0
    pct_warn = (warning / total * 100) if total else 0
    pct_fail = (failing / total * 100) if total else 0

    print(bold("  SUMMARY"))
    print()
    print(f"  {green('PASS')}  {passing:>3} / {total}  ({pct_pass:.0f}%)")
    print(f"  {yellow('WARN')}  {warning:>3} / {total}  ({pct_warn:.0f}%)")
    print(f"  {red('FAIL')}  {failing:>3} / {total}  ({pct_fail:.0f}%)")
    print()

    if violation_counter:
        print(bold("  MOST COMMON VIOLATIONS"))
        print()
        for violation, count in violation_counter.most_common(8):
            print(f"  {count:>3}x  {violation}")
        print()

    return 0 if failing == 0 else 1


def _categorise_issue(issue: str) -> str:
    """Map a raw issue string to a coarse violation category."""
    lower = issue.lower()
    if "type prefix" in lower or "type'" in lower or "valid" in lower:
        return "missing or invalid type prefix"
    if "tool attribution" in lower or "generated by" in lower:
        return "tool/AI attribution in message"
    if "vague" in lower or "banned" in lower or "too vague" in lower:
        return "vague or banned summary phrase"
    if "lowercase" in lower and "type" in lower:
        return "type not lowercase"
    if "lowercase" in lower and "scope" in lower:
        return "scope not lowercase"
    if "period" in lower:
        return "trailing period on summary"
    if "imperative" in lower or "tense" in lower:
        return "non-imperative summary tense"
    if "char" in lower or "limit" in lower or "length" in lower:
        return "subject line too long"
    if "empty" in lower:
        return "empty summary"
    return "other violation"


# ---------------------------------------------------------------------------
# Subcommand: report
# ---------------------------------------------------------------------------

def cmd_report(args: argparse.Namespace) -> int:
    commits = load_history(args.input)
    today = date.today().isoformat()

    results: List[Tuple[dict, ValidationResult]] = []
    for commit in commits:
        msg = commit.get("message", "")
        results.append((commit, validate_message(msg, type_prefix=not args.no_type_prefix)))

    total   = len(results)
    passing = sum(1 for _, r in results if r.status == "PASS")
    warning = sum(1 for _, r in results if r.status == "WARN")
    failing = sum(1 for _, r in results if r.status == "FAIL")

    violation_counter: Counter = Counter()
    for _, r in results:
        for issue in r.issues:
            violation_counter[_categorise_issue(issue)] += 1

    lines: List[str] = []
    add = lines.append

    add("# Commit Message Quality Report")
    add("")
    add(f"**Source file:** `{os.path.basename(args.input)}`  ")
    add(f"**Report generated:** {today}  ")
    add(f"**Total commits analysed:** {total}  ")
    add("")

    add("## Executive Summary")
    add("")
    add("| Status | Count | Percentage |")
    add("|--------|------:|-----------:|")
    pct_p = f"{passing / total * 100:.0f}%" if total else "—"
    pct_w = f"{warning / total * 100:.0f}%" if total else "—"
    pct_f = f"{failing / total * 100:.0f}%" if total else "—"
    add(f"| PASS | {passing} | {pct_p} |")
    add(f"| WARN | {warning} | {pct_w} |")
    add(f"| FAIL | {failing} | {pct_f} |")
    add(f"| **Total** | **{total}** | 100% |")
    add("")

    if violation_counter:
        add("## Most Common Violations")
        add("")
        add("| Violation | Count |")
        add("|-----------|------:|")
        for violation, count in violation_counter.most_common():
            add(f"| {violation} | {count} |")
        add("")

    add("## Per-Commit Results")
    add("")
    add("| Hash | Status | Author | Message |")
    add("|------|--------|--------|---------|")
    for commit, result in results:
        hash_str = commit.get("hash", "???????")
        author   = commit.get("author", "")
        # Escape pipes in message
        msg_safe = result.message.replace("|", "\\|")
        add(f"| `{hash_str}` | {result.status} | {author} | {msg_safe} |")
    add("")

    # Detailed section for non-passing commits
    non_passing = [(c, r) for c, r in results if r.status != "PASS"]
    if non_passing:
        add("## Commits Requiring Attention")
        add("")
        for commit, result in non_passing:
            hash_str = commit.get("hash", "???????")
            author   = commit.get("author", "")
            cdate    = commit.get("date", "")
            add(f"### `{hash_str}` — {result.status}")
            add("")
            add(f"- **Author:** {author}")
            add(f"- **Date:** {cdate}")
            add(f"- **Message:** `{result.message}`")
            add("")
            if result.issues:
                add("**Issues:**")
                add("")
                for issue in result.issues:
                    add(f"- {issue}")
                add("")
            if result.suggestion:
                add(f"**Suggested rewrite:** `{result.suggestion}`")
                add("")
    else:
        add("## Commits Requiring Attention")
        add("")
        add("_All commits pass. No attention required._")
        add("")

    add("## Validation Rules Reference")
    add("")
    add("| Rule | Threshold | Severity |")
    add("|------|-----------|----------|")
    if args.no_type_prefix:
        add("| Type prefix | not required (`--no-type-prefix`); plain imperative subjects accepted | — |")
    else:
        add("| Type prefix required | `<type>: <summary>` or `<type>(<scope>): <summary>` | FAIL |")
    add(f"| Valid types | {', '.join(f'`{t}`' for t in sorted(VALID_TYPES))} | FAIL |")
    add("| Type must be lowercase | — | FAIL |")
    add("| Scope, when present, must be nonempty lowercase kebab-case | — | FAIL |")
    add("| Summary must be imperative | no trailing -ed/-ing on first word | WARN |")
    add("| No trailing period | — | FAIL |")
    add(f"| Subject line length (soft) | ≤{LENGTH_SOFT} chars | WARN |")
    add(f"| Subject line length (hard) | ≤{LENGTH_HARD} chars | FAIL |")
    add("| Banned summary phrases | update, wip, misc, update stuff, fix stuff, change code | FAIL |")
    add("| No tool attribution | generated by, via claude, via copilot, chatgpt, ai assistant; AI-tool trailers other than `Assisted-by:`, `Claude-Session:` and `Audit-*` | FAIL |")
    add('| Accepted as-is | message body, `BREAKING CHANGE:` footer, git `Revert "..."` subject | — |')
    add("")

    add("---")
    add("_Report generated by commit_validator.py — dev-git-commit-message skill_")

    report_text = "\n".join(lines)

    if args.output:
        try:
            with open(args.output, "w", encoding="utf-8") as fh:
                fh.write(report_text)
        except (OSError, UnicodeError) as exc:
            print(f"ERROR: cannot write {args.output}: {exc}", file=sys.stderr)
            return 1
        print(f"Report written to: {args.output}")
    else:
        print(report_text)

    return 0


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="commit_validator.py",
        description="Conventional Commit Message Validator and Linter (stdlib only)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/commit_validator.py validate --message "feat(auth): add refresh token rotation"
  python scripts/commit_validator.py validate --no-type-prefix --message "Add refresh token rotation"
  python scripts/commit_validator.py lint --input data/sample-commit-history.json
  python scripts/commit_validator.py report --input data/sample-commit-history.json
  python scripts/commit_validator.py report --input data/sample-commit-history.json --output report.md
        """.strip(),
    )
    parser.add_argument(
        "--no-color",
        action="store_true",
        help="Disable ANSI colour output (useful for CI logs)",
    )

    sub = parser.add_subparsers(dest="command", metavar="COMMAND")
    sub.required = True

    # Shared by every subcommand: opt out of the type-prefix rule only.
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument(
        "--no-type-prefix",
        action="store_true",
        help=(
            "Accept plain imperative subjects (no '<type>(<scope>):' prefix), for repos "
            "whose convention is short imperative subjects. Skips only the type/scope "
            "rule; length, period, imperative-mood, banned-phrase and trailer rules still apply"
        ),
    )

    # --- validate ---
    p_validate = sub.add_parser(
        "validate",
        parents=[common],
        help="Validate a single commit message",
        description=(
            "Validate one commit message against Conventional Commits rules. "
            "Checks type prefix, valid type, scope case, imperative mood, "
            "length, trailing period, banned phrases, and tool attribution."
        ),
    )
    p_validate.add_argument(
        "--message", "-m",
        required=True,
        metavar="MSG",
        help="Commit message to validate (subject, optional body and trailers)",
    )

    # --- lint ---
    p_lint = sub.add_parser(
        "lint",
        parents=[common],
        help="Lint a batch of commit messages from a JSON history file",
        description=(
            "Read a JSON commit history array and validate every message. "
            "Prints per-message PASS/WARN/FAIL, then a summary with "
            "statistics and most common violation types."
        ),
    )
    p_lint.add_argument(
        "--input", "-i",
        required=True,
        metavar="JSON_FILE",
        help="Path to commit history JSON file (array of commit objects)",
    )

    # --- report ---
    p_report = sub.add_parser(
        "report",
        parents=[common],
        help="Generate a full Markdown commit quality report",
        description=(
            "Produce a full Markdown report: executive summary, violation "
            "breakdown, per-commit table, and detailed attention list for "
            "non-passing commits."
        ),
    )
    p_report.add_argument(
        "--input", "-i",
        required=True,
        metavar="JSON_FILE",
        help="Path to commit history JSON file",
    )
    p_report.add_argument(
        "--output", "-o",
        metavar="FILE",
        help="Write Markdown report to this file (default: stdout)",
    )

    return parser


def main() -> int:
    global USE_COLOR

    # Handle --no-color before full parse so it works in any position
    if "--no-color" in sys.argv:
        USE_COLOR = False
        sys.argv = [a for a in sys.argv if a != "--no-color"]

    parser = build_parser()
    args = parser.parse_args()

    dispatch = {
        "validate": cmd_validate,
        "lint":     cmd_lint,
        "report":   cmd_report,
    }
    return dispatch[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
